check for outdated framework version

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -14,6 +14,20 @@ jobs:
     if: ${{ !startsWith(github.head_ref, 'version-bump') }}
     steps:
       - uses: actions/checkout@v3
+        with:
+          ref: ${{ github.event.pull_request.head.sha }}
+      - run: |
+          # Check for outdated framework version
+          current_version=$(node -pe "require('${{ github.workspace }}/package.json').version")
+          git fetch origin ${{ github.base_ref }}
+          git checkout ${{ github.base_ref }}
+          main_version=$(node -pe "require('${{ github.workspace }}/package.json').version")
+
+          if [ "$main_version" != "$current_version" ]; then
+           echo "Error: Package version on current branch ($current_package_version) does not match the one on ${{ github.base_ref }} branch ($main_package_version)"
+          exit 1
+          fi
+      - uses: actions/checkout@v3
       - uses: ./.github/actions/setup
       - run: yarn build
   lint:
